version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./database:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: urlshortener
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - urlshortener
    restart: always

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    ports:
      - 127.0.0.1:8081:8081
    links:
      - mongo
    networks:
      - urlshortener
    depends_on:
      - mongo
    restart: always

networks:
  urlshortener:
    driver: bridge

